config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "forums#index"

  resources :forums do
    resources :topics
  end
end

app/models/forum.rb
class Forum < ActiveRecord::Base

  has_many :topics, dependent: :delete_all
  validates :title, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :topic
  belongs_to :author, class_name: 'User'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :forum
  has_many :posts
  accepts_nested_attributes_for :posts
  validates :subject, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController

  def index
    @forums = Forum.all
  end

  def new
    @forum = Forum.new
  end

  def create
    @forum = Forum.new(forum_params)

    if @forum.save
      flash[:notice] = "Forum has been created!"
      redirect_to @forum
    else
      flash.now[:alert] = "Forum has not been created."
      render "new"
    end
  end

  def show
    @forum = Forum.find(params[:id])
  end

  def edit
    @forum = Forum.find(params[:id])
  end

  def update
      @forum = Forum.find(params[:id])
        if @forum.update(forum_params)
          flash[:notice] = "Forum has been updated."
          redirect_to @forum
        else
          flash.now[:alert] = "Forum has not been updated."
          render "edit"
        end
  end

  def destroy
    @forum = Forum.find(params[:id])
    @forum.destroy

    flash[:notice] = "Forum has been deleted."
    redirect_to forums_path
  end

private

  def forum_params
    params.require(:forum).permit(:title, :description)
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

before_action :set_forum
before_action :set_topic, only: [:show, :edit, :update, :destroy]

  def new
    @topic = @forum.topics.build
    @topic.posts.build
  end


  def create
    @topic = @forum.topics.build(topic_params)
    @topic.posts.first.author = current_user

    if @topic.save
      flash[:notice] = "Topic has been created."
      redirect_to [@forum, @topic]
    else
    flash.now[:alert] = "Topic has not been created."
    render "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @topic.update(topic_params)
      flash[:notice] = "Topic has been updated."
      redirect_to [@forum ,@topic]
    else
      flash.now[:alert] = "Topic has not been updated."
      render "edit"
    end
  end




  private
  def set_forum
    @forum = Forum.find(params[:forum_id])
  end

  def set_topic
    @topic = @forum.topics.find(params[:id])
  end

  def topic_params
    params.require(:topic).permit(:subject, posts_attributes: [:text])

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/forums/_form.html.erb
<%= simple_form_for(forum) do |f| %>

<% if forum.errors.any? %>
<ul>
 <% forum.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
    <% end %>
</ul>
   <% end %>

  <p>
    <%= f.input :title %><br>
  </p>

  <p>
    <%= f.input :description %><br>
  </p>
  <%= f.button :submit %>
<% end %>

app/views/forums/edit.html.erb
<%= render "form", forum: @forum %>

app/views/forums/index.html.erb
<%= link_to "New Forum", new_forum_path %>

<% @forums.each do |forum| %>
  <h2><%= link_to forum.title, forum %></h2>
  <p><%=  forum.description %></p>
  <% end %>

app/views/forums/new.html.erb
<h1>New Forum</h1>

<%= render "form", forum: @forum %>

app/views/forums/show.html.erb
<h1><%= @forum.title %></h1>
  <p><%= @forum.description %></p>

  <ul>
    <% @forum.topics.each do |topic| %>
      <li>
        <h3><%= link_to topic.subject, [@forum, topic] %></h3>
      </li>
  </ul>
  <% end %><br>

  <%= link_to "Edit Forum", edit_forum_path(@forum) %><br>

  <%= link_to "Delete Forum", forum_path(@forum), method: :delete, data: {confirm: "Are you sure you wish to delete this forum?"} %><br>

  <%= link_to "New Topic", new_forum_topic_path(@forum) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Forums</title>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>

<% if user_signed_in? %>
  <div class="navbar-right">
    <p class="navbar-text">
      Signed in as <%= current_user.email %>
    </p>
    <ul class="nav navbar-nav">
    <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
  </ul>
  </div>
<% end %>


<div>
  <% unless user_signed_in? %>
    <li>
      <% "active" if current_page?("/users/sign_up") %>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>

    <li>
      <% "active" if current_page?("/users/sign_in") %>
      <%= link_to "Sign in", new_user_session_path %>
    </li>
</div>
<% end %>

<% flash.each do |key, message| %>
<div><%= message %></div>
<% end %>

<%= yield %>

    </body>
</html>

app/views/topics/_form.html.erb
<%= simple_form_for([forum, topic]) do |f| %>

<% if @forum.errors.any? %>
<ul>
 <% @forum.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
    <% end %>
</ul>
   <% end %>

  <p>
    <%= f.input :subject %><br>
  </p>

  <%= f.fields_for :posts do |post| %>
    <p>
      <%= post.input :text %>
    </p>
  <% end %>

  <%= f.button :submit %>
<% end %>

app/views/topics/edit.html.erb
<%= render "form", forum: @forum, topic: @topic %>

app/views/topics/new.html.erb
<%= render "form", forum: @forum, topic: @topic %>

app/views/topics/show.html.erb
<%= simple_format(@topic.subject) %>

<table id="attributes">

    <tr>
        <th>Created:</th>
        <td><%= time_ago_in_words(@topic.created_at) %>
            ago</td>
    </tr>
</table>

<ul>
    <li><%= link_to "Edit Topic", [:edit, @forum, @topic] %></li>
</ul>

<ul id="topics">
    <% @topic.posts.each do |post| %>
    <% if post.author.present? %>
      Author: <%= post.author.email %>
    <% else %>
      Author: Anonymous
    <% end %>
    <%= markdown(post.text) %>
    <% end %>
</ul>